# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=1000)),
                ('longitude', models.CharField(max_length=1000, null=True)),
                ('latitude', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
